#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
write_envrc.sh — generate a standard direnv .envrc for worktrees

Usage:
  write_envrc.sh [--root DIR] [--config-slug SLUG] [--env-file NAME] [--template-file NAME] [--force]

Defaults:
  --root: auto-detect via `git rev-parse --show-toplevel` (fallback: cwd)
  --config-slug: medicalassistant_mcp   (maps to ~/.config/<slug>/.env)
  --env-file: .env
  --template-file: .env.template

Notes:
  - Writes <root>/.envrc
  - Does NOT run `direnv allow` (see bootstrap_direnv.sh)
EOF
}

ROOT=""
CONFIG_SLUG="medicalassistant_mcp"
ENV_FILE_NAME=".env"
TEMPLATE_FILE_NAME=".env.template"
FORCE="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      ROOT="${2:-}"; shift 2;;
    --config-slug)
      CONFIG_SLUG="${2:-}"; shift 2;;
    --env-file)
      ENV_FILE_NAME="${2:-}"; shift 2;;
    --template-file)
      TEMPLATE_FILE_NAME="${2:-}"; shift 2;;
    --force)
      FORCE="1"; shift;;
    -h|--help)
      usage; exit 0;;
    *)
      echo "Unknown arg: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -z "$ROOT" ]]; then
  ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
fi
cd "$ROOT" || exit 1

OUT="$ROOT/.envrc"
if [[ -f "$OUT" && "$FORCE" != "1" ]]; then
  echo ".envrc already exists: $OUT (use --force to overwrite)" >&2
  exit 0
fi

cat > "$OUT" <<EOF
# Generated by direnv-envrc-bootstrap/scripts/write_envrc.sh

# Always operate from repo root (works even if you cd into subdirs)
ROOT="\$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "\$ROOT" || exit 1

ENV_FILE="\$ROOT/${ENV_FILE_NAME}"
TEMPLATE="\$ROOT/${TEMPLATE_FILE_NAME}"

# Seed .env for new worktrees (Codex creates them later, so do it here)
if [[ ! -f "\$ENV_FILE" ]]; then
  umask 077

  # 1) Canonical local secrets location (best for dev)
  SRC_CFG="\${HOME}/.config/${CONFIG_SLUG}/.env"
  if [[ -f "\$SRC_CFG" ]]; then
    cat "\$SRC_CFG" > "\$ENV_FILE"
    echo "✓ Seeded \$ENV_FILE from \$SRC_CFG"
  else
    # 2) Fallback: copy from any other worktree that has a .env (even if gitignored)
    CUR="\$ROOT"
    while IFS= read -r WT; do
      [[ -n "\$WT" ]] || continue
      [[ "\$WT" == "\$CUR" ]] && continue
      if [[ -f "\$WT/${ENV_FILE_NAME}" ]]; then
        cat "\$WT/${ENV_FILE_NAME}" > "\$ENV_FILE"
        echo "✓ Seeded \$ENV_FILE from worktree: \$WT/${ENV_FILE_NAME}"
        break
      fi
    done < <(git worktree list --porcelain 2>/dev/null | awk '\$1=="worktree"{print \$2}')
  fi

  # Optional template fallback (won't overwrite if .env now exists)
  if [[ ! -f "\$ENV_FILE" && -f "\$TEMPLATE" ]]; then
    cat "\$TEMPLATE" > "\$ENV_FILE"
    echo "⚠️ Created \$ENV_FILE from \$TEMPLATE (no REAL source found)"
  fi
fi

# Load env vars (doesn't error if .env is still missing)
dotenv_if_exists "\$ENV_FILE"
EOF

echo "✓ Wrote $OUT"
